language: haskell

script:
 - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
 - cabal install doctest
 - doctest -isrc -optP-include -optPdist/build/autogen/cabal_macros.h `find src/ -name '*.hs'`
